-- No-op: VIGENTE is the canonical status for formalized contracts.
-- This migration used to add a CONTRATO enum value, but the application now
-- keeps the original estado_contrato_enum values from veredas_sarchi_bd_v1.sql.
